name: lawang
description: Aplikasi Statistik Indonesia - Data terpercaya dan komprehensif.
publish_to: 'none' # Mencegah publikasi yang tidak disengaja
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

# =================== DEPENDENCIES ===================
# Semua paket aplikasi Anda ada di sini, diurutkan secara alfabet.
dependencies:
  flutter:
    sdk: flutter
  csv: ^5.1.1
  fl_chart: ^0.68.0
  http: ^1.2.1
  package_info_plus: ^4.2.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  video_player: ^2.8.13
  flutter_svg: ^2.3.0

# =================== DEV DEPENDENCIES ===================
dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: ^1.2.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# =================== FLUTTER CONFIGURATION ===================
flutter:
  uses-material-design: true
  
  # Aset gambar, video, dan animasi
  assets:
    - assets/images/logo.png
    - assets/images/logo-bps.svg
    - assets/images/logo_white.png
    - assets/animations/ringan.mp4
    - assets/data/ranking_pdrb_jateng.csv
  
  # Konfigurasi Font
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

# =================== LAUNCHER ICON CONFIGURATION ===================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21